### ISSUE TITLE
The keypoints output file generated after testing has a v value of 1 for all 294 key points

### ISSUE THREAD

**Issue by haoli-zbdbc** [ShenhanQian/KGDet#11]
Following your steps exactly, why is each key point in the generated JSON file 1.0? As shown in the figure:
![图片](https://github.com/ShenhanQian/KGDet/assets/50076227/3a198776-7c81-47f4-9a6e-6d8970424ebb)
Will the visualization result in all the key points appearing because I haven't set them? Is there a problem with the prediction model?
![图片](https://github.com/ShenhanQian/KGDet/assets/50076227/b35ae76d-03db-4eb4-a9e0-cca0e583e27d)
There is no problem with the test, but it is strange to see 294 key points in the output file with all v being 1！！！
![图片](https://github.com/ShenhanQian/KGDet/assets/50076227/1d6b622c-b36f-4d3c-8b46-d31054e9189c)

**Comment by haoli-zbdbc** [comment]
I have solved this problem and thank you for your great work！！！！

**Comment by Baicheng42** [comment]
How did you solve it, please?

**Comment by Baicheng42** [comment]
I met the same problem. Could you please give me some advise?

**Comment by haoli-zbdbc** [comment]
@Baicheng42 Hi, it's been a long time since I've used this repository. I can only give you a general idea, please try it: The 294 points are all the points and should determine the index of the landmark based on the category recognized by the bbox. 294 points are divided into three groups: one coordinate x y v and the last v=1 is visual, let's say category 0 is points 0-13 and category 1 is 14-36, Just find the category with the highest bbox score, and find the corresponding idx-idy.
![图片](https://github.com/user-attachments/assets/28cbde8c-84a0-4ae5-ac37-704d07f01142)

**Comment by Baicheng42** [comment]
@haoli-zbdbc Thanks! I fixed it.
