### ISSUE TITLE
Question about dataset for training ?

### ISSUE THREAD

**Issue by ThorPham** [ShenhanQian/KGDet#7]
Thank you for great research. I have a question about field keypoints in dataset. Why number keypoint very large 882 while max keypoint in deepfastion  is 38 .

**Comment by ShenhanQian** [comment]
Deepfashion2 defines 13 categories of clothes. Each category has an independent definition of keypoints. The total number of all the keypoints of the 13 categories is 293. Since a keypoint is represented by `(x, y, confidence)`, the final number of output is `293 * 3 = 882`.

**Comment by ThorPham** [comment]
@ShenhanQian  thank you for your support. I want to write script to test single image. What step preprocessing i need ?
I visualize keypoints and box but a lot of keypoint in pictures. How can i preprocessing keypoints after model inference.
![Screenshot from 2022-08-08 14-20-33](https://user-images.githubusercontent.com/33828708/183362388-8bbf9438-0c4f-4cac-9663-6f149d1a61ee.png)

**Comment by ShenhanQian** [comment]
You see a lot of points because you have plotted all the 293 keypoints of all 13 categories. 

You just need to select the keypoints of the predicted category for each clothing instance.

**Comment by ThorPham** [comment]
@ShenhanQian  oh my god. My bad.
I am use function inference_detector in mmdetection to inference. Do i need to use any preprocessing like NMS or something else to get final output. I see a lot of box in same object

**Comment by ThorPham** [comment]
![Screenshot from 2022-08-08 14-40-58](https://user-images.githubusercontent.com/33828708/183365497-bf1ed092-7adb-420f-8d00-d5aef1cb4db6.png)
Can you explain  Why lenght of detection is 13 correspond to 13 class but score only 10.

**Comment by ShenhanQian** [comment]
The output is already processed by NMS. For each instance, if multiple bbox results are provided, they should belong to different clothing categories. You can either keep all of them for a high recall rate or simply take the one with the highest confidence score.

**Comment by ThorPham** [comment]
Thank you so much.
